version: '3.9'

services:
  aerospike:
    image: aerospike/aerospike-server
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "asinfo", "-v", "status"]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      aerospike:
        condition: service_healthy
