// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/app.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RollNo        int64                  `protobuf:"varint,1,opt,name=roll_no,json=rollNo,proto3" json:"roll_no,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Physics       int64                  `protobuf:"varint,3,opt,name=physics,proto3" json:"physics,omitempty"`
	Chemistry     int64                  `protobuf:"varint,4,opt,name=chemistry,proto3" json:"chemistry,omitempty"`
	Biology       int64                  `protobuf:"varint,5,opt,name=biology,proto3" json:"biology,omitempty"`
	Maths         int64                  `protobuf:"varint,6,opt,name=maths,proto3" json:"maths,omitempty"`
	English       int64                  `protobuf:"varint,7,opt,name=english,proto3" json:"english,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertUserRequest) Reset() {
	*x = InsertUserRequest{}
	mi := &file_proto_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertUserRequest) ProtoMessage() {}

func (x *InsertUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertUserRequest.ProtoReflect.Descriptor instead.
func (*InsertUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{0}
}

func (x *InsertUserRequest) GetRollNo() int64 {
	if x != nil {
		return x.RollNo
	}
	return 0
}

func (x *InsertUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InsertUserRequest) GetPhysics() int64 {
	if x != nil {
		return x.Physics
	}
	return 0
}

func (x *InsertUserRequest) GetChemistry() int64 {
	if x != nil {
		return x.Chemistry
	}
	return 0
}

func (x *InsertUserRequest) GetBiology() int64 {
	if x != nil {
		return x.Biology
	}
	return 0
}

func (x *InsertUserRequest) GetMaths() int64 {
	if x != nil {
		return x.Maths
	}
	return 0
}

func (x *InsertUserRequest) GetEnglish() int64 {
	if x != nil {
		return x.English
	}
	return 0
}

type InsertUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertUserResponse) Reset() {
	*x = InsertUserResponse{}
	mi := &file_proto_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertUserResponse) ProtoMessage() {}

func (x *InsertUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertUserResponse.ProtoReflect.Descriptor instead.
func (*InsertUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{1}
}

func (x *InsertUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RollNo        int64                  `protobuf:"varint,1,opt,name=roll_no,json=rollNo,proto3" json:"roll_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetRollNo() int64 {
	if x != nil {
		return x.RollNo
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RollNo        int64                  `protobuf:"varint,1,opt,name=roll_no,json=rollNo,proto3" json:"roll_no,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Physics       int64                  `protobuf:"varint,3,opt,name=physics,proto3" json:"physics,omitempty"`
	Chemistry     int64                  `protobuf:"varint,4,opt,name=chemistry,proto3" json:"chemistry,omitempty"`
	Biology       int64                  `protobuf:"varint,5,opt,name=biology,proto3" json:"biology,omitempty"`
	Maths         int64                  `protobuf:"varint,6,opt,name=maths,proto3" json:"maths,omitempty"`
	English       int64                  `protobuf:"varint,7,opt,name=english,proto3" json:"english,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetRollNo() int64 {
	if x != nil {
		return x.RollNo
	}
	return 0
}

func (x *GetUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserResponse) GetPhysics() int64 {
	if x != nil {
		return x.Physics
	}
	return 0
}

func (x *GetUserResponse) GetChemistry() int64 {
	if x != nil {
		return x.Chemistry
	}
	return 0
}

func (x *GetUserResponse) GetBiology() int64 {
	if x != nil {
		return x.Biology
	}
	return 0
}

func (x *GetUserResponse) GetMaths() int64 {
	if x != nil {
		return x.Maths
	}
	return 0
}

func (x *GetUserResponse) GetEnglish() int64 {
	if x != nil {
		return x.English
	}
	return 0
}

var File_proto_app_proto protoreflect.FileDescriptor

const file_proto_app_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/app.proto\x12\x03app\x1a\x1cgoogle/api/annotations.proto\"\xc2\x01\n" +
	"\x11InsertUserRequest\x12\x17\n" +
	"\aroll_no\x18\x01 \x01(\x03R\x06rollNo\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aphysics\x18\x03 \x01(\x03R\aphysics\x12\x1c\n" +
	"\tchemistry\x18\x04 \x01(\x03R\tchemistry\x12\x18\n" +
	"\abiology\x18\x05 \x01(\x03R\abiology\x12\x14\n" +
	"\x05maths\x18\x06 \x01(\x03R\x05maths\x12\x18\n" +
	"\aenglish\x18\a \x01(\x03R\aenglish\".\n" +
	"\x12InsertUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\aroll_no\x18\x01 \x01(\x03R\x06rollNo\"\xc0\x01\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\aroll_no\x18\x01 \x01(\x03R\x06rollNo\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aphysics\x18\x03 \x01(\x03R\aphysics\x12\x1c\n" +
	"\tchemistry\x18\x04 \x01(\x03R\tchemistry\x12\x18\n" +
	"\abiology\x18\x05 \x01(\x03R\abiology\x12\x14\n" +
	"\x05maths\x18\x06 \x01(\x03R\x05maths\x12\x18\n" +
	"\aenglish\x18\a \x01(\x03R\aenglish2\xab\x01\n" +
	"\n" +
	"AppService\x12P\n" +
	"\x06Insert\x12\x16.app.InsertUserRequest\x1a\x17.app.InsertUserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/insert\x12K\n" +
	"\x03Get\x12\x13.app.GetUserRequest\x1a\x14.app.GetUserResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/get/{roll_no}B\tZ\a./protob\x06proto3"

var (
	file_proto_app_proto_rawDescOnce sync.Once
	file_proto_app_proto_rawDescData []byte
)

func file_proto_app_proto_rawDescGZIP() []byte {
	file_proto_app_proto_rawDescOnce.Do(func() {
		file_proto_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_proto_rawDesc), len(file_proto_app_proto_rawDesc)))
	})
	return file_proto_app_proto_rawDescData
}

var file_proto_app_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_app_proto_goTypes = []any{
	(*InsertUserRequest)(nil),  // 0: app.InsertUserRequest
	(*InsertUserResponse)(nil), // 1: app.InsertUserResponse
	(*GetUserRequest)(nil),     // 2: app.GetUserRequest
	(*GetUserResponse)(nil),    // 3: app.GetUserResponse
}
var file_proto_app_proto_depIdxs = []int32{
	0, // 0: app.AppService.Insert:input_type -> app.InsertUserRequest
	2, // 1: app.AppService.Get:input_type -> app.GetUserRequest
	1, // 2: app.AppService.Insert:output_type -> app.InsertUserResponse
	3, // 3: app.AppService.Get:output_type -> app.GetUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_app_proto_init() }
func file_proto_app_proto_init() {
	if File_proto_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_proto_rawDesc), len(file_proto_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_app_proto_goTypes,
		DependencyIndexes: file_proto_app_proto_depIdxs,
		MessageInfos:      file_proto_app_proto_msgTypes,
	}.Build()
	File_proto_app_proto = out.File
	file_proto_app_proto_goTypes = nil
	file_proto_app_proto_depIdxs = nil
}
